apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-deployment
  labels:
    app: facebook-clone
spec:
  replicas: 2
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
        - name: backend
          image: lucasfsn/facebook-clone-server:1.0-windows
          resources:
            limits:
              cpu: '200m'
              memory: '600Mi'
          env:
            - name: MONGO_CONNECTION_STRING
              valueFrom:
                secretKeyRef:
                  name: backend-secrets
                  key: MONGO_CONNECTION_STRING
            - name: CLIENT_SECRET
              valueFrom:
                secretKeyRef:
                  name: backend-secrets
                  key: CLIENT_SECRET
            - name: CLOUDINARY_CLOUD_NAME
              valueFrom:
                secretKeyRef:
                  name: backend-secrets
                  key: CLOUDINARY_CLOUD_NAME
            - name: CLOUDINARY_API_SECRET
              valueFrom:
                secretKeyRef:
                  name: backend-secrets
                  key: CLOUDINARY_API_SECRET
            - name: CLOUDINARY_API_KEY
              valueFrom:
                secretKeyRef:
                  name: backend-secrets
                  key: CLOUDINARY_API_KEY
---
apiVersion: v1
kind: Service
metadata:
  name: backend-service
  labels:
    app: facebook-clone
spec:
  selector:
    app: backend
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000
