apiVersion: v1
kind: ConfigMap
metadata:
  name: keycloak-config
data:
  KC_DB: 'postgres'
  KC_DB_URL: 'jdbc:postgresql://postgres-service:5432/keycloak'
  KC_DB_URL_DATABASE: 'keycloak'
  KC_DB_URL_HOST: 'postgres-service'
  KC_DB_URL_PORT: '5432'
  KEYCLOAK_ADMIN: 'keycloak'
  KEYCLOAK_ADMIN_PASSWORD: 'keycloak'
---
apiVersion: v1
kind: Service
metadata:
  name: keycloak-service
  labels:
    app: facebook-clone
spec:
  selector:
    app: keycloak
  ports:
    - port: 8080
      targetPort: 8080
      protocol: TCP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: keycloak-deployment
  labels:
    app: facebook-clone
spec:
  replicas: 1
  selector:
    matchLabels:
      app: keycloak
  template:
    metadata:
      labels:
        app: keycloak
    spec:
      containers:
        - name: keycloak
          image: quay.io/keycloak/keycloak:24.0.4
          args: ['start-dev']
          resources:
            limits:
              cpu: '1000m'
              memory: '2000Mi'
          env:
            - name: KC_DB
              valueFrom:
                configMapKeyRef:
                  name: keycloak-config
                  key: KC_DB
            - name: KC_DB_URL
              valueFrom:
                configMapKeyRef:
                  name: keycloak-config
                  key: KC_DB_URL
            - name: KC_DB_URL_DATABASE
              valueFrom:
                configMapKeyRef:
                  name: keycloak-config
                  key: KC_DB_URL_DATABASE
            - name: KC_DB_URL_HOST
              valueFrom:
                configMapKeyRef:
                  name: keycloak-config
                  key: KC_DB_URL_HOST
            - name: KC_DB_URL_PORT
              valueFrom:
                configMapKeyRef:
                  name: keycloak-config
                  key: KC_DB_URL_PORT
            - name: KEYCLOAK_ADMIN
              valueFrom:
                configMapKeyRef:
                  name: keycloak-config
                  key: KEYCLOAK_ADMIN
            - name: KEYCLOAK_ADMIN_PASSWORD
              valueFrom:
                configMapKeyRef:
                  name: keycloak-config
                  key: KEYCLOAK_ADMIN_PASSWORD
            - name: KC_DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: postgres-secret
                  key: POSTGRES_PASSWORD
            - name: KC_DB_USERNAME
              valueFrom:
                secretKeyRef:
                  name: postgres-secret
                  key: POSTGRES_USER
          ports:
            - containerPort: 8080
              protocol: TCP
