apiVersion: v1
kind: ConfigMap
metadata:
  name: postgres-config
data:
  setup.sql: |
    CREATE DATABASE keycloak;
---
apiVersion: v1
kind: Secret
metadata:
  name: postgres-secret
  labels:
    app: facebook-clone
type: Opaque
data:
  POSTGRES_USER: cm9vdA==
  POSTGRES_PASSWORD: cm9vdA==
  POSTGRES_DB: cm9vdA==
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgres-pvc
  labels:
    app: facebook-clone
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: standard
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres-deployment
  labels:
    app: facebook-clone
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgres
  template:
    metadata:
      labels:
        app: postgres
    spec:
      containers:
        - name: postgres
          image: postgres:latest
          ports:
            - containerPort: 5432
              protocol: TCP
          resources:
            limits:
              cpu: '150m'
              memory: '256Mi'
          volumeMounts:
            - name: postgres-config
              mountPath: /docker-entrypoint-initdb.d/
            - name: postgres-pvc
              mountPath: /var/lib/postgresql/data
              readOnly: false
          env:
            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  name: postgres-secret
                  key: POSTGRES_USER
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: postgres-secret
                  key: POSTGRES_PASSWORD
            - name: POSTGRES_DB
              valueFrom:
                secretKeyRef:
                  name: postgres-secret
                  key: POSTGRES_DB
      volumes:
        - name: postgres-config
          configMap:
            name: postgres-config
        - name: postgres-pvc
          persistentVolumeClaim:
            claimName: postgres-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: postgres-service
  labels:
    app: facebook-clone
spec:
  selector:
    app: postgres
  clusterIP: None
  ports:
    - port: 5432
      targetPort: 5432
